### ISSUE TITLE
How do I change the config to trigger commands with "!" ? 

### ISSUE THREAD

**Issue by beafb** [b1naryth1ef/disco#108]
Hi there,

I don't find how to change the settings of the bot, instead of mentioning the bot i'd like to start command with ! or other..

Do you know how i can do it ?

Thanks in advance

**Comment by Alkali-Metal** [comment]
Modify the bot's configuration to have `commands_prefix` in the `bot` section under the config.

ex:
```yaml
token: "TOKEN"
bot:
  commands_prefix: "!"
```
